#include <iostream>
#include <sqlite3.h>
#include <string.h>
#include <sstream>
#include <vector>
namespace std
{
const char* createTable_PopEstNationStatePr = "DROP TABLE IF EXISTS POP_EST_NATION_STATE_PR;\
	CREATE TABLE POP_EST_NATION_STATE_PR(						\
	SUMLEV		INTEGER	REFERENCES SUMLEV(SUMLEV_Cd),							\
	REGION		INTEGER REFERENCES REGION(REGION_Cd),							\
	DIVISION	INTEGER REFERENCES DIVISION(DIVISION_Cd),							\
	STATE		INTEGER,							\
	NAME		VARCHAR(255) PRIMARY KEY,					\
	CENSUS2010POP	INTEGER,							\
	ESTIMATEBASE2010	INTEGER,						\
	POPESTIMATE2010	INTEGER,							\
	POPESTIMATE2011	INTEGER,							\
	POPESTIMATE2012	INTEGER,							\
	NPOPCHG_2010	INTEGER,							\
	NPOPCHG_2011	INTEGER,							\
	NPOPCHG_2012	INTEGER,							\
	BIRTHS2010	INTEGER,							\
	BIRTHS2011	INTEGER,							\
	BIRTHS2012	INTEGER,							\
	DEATH2010	INTEGER,							\
	DEATH2011	INTEGER,							\
	DEATH2012	INTEGER,							\
	NATURALINC2010	INTEGER,							\
	NATURALINC2011	INTEGER,							\
	NATURALINC2012	INTEGER,							\
	INTERNATIONALMIG2010	INTEGER,						\
	INTERNATIONALMIG2011	INTEGER,						\
	INTERNATIONALMIG2012	INTEGER,						\
	DOMESTICMIG2010	INTEGER,							\
	DOMESTICMIG2011	INTEGER,							\
	DOMESTICMIG2012	INTEGER,							\
	NETMIG2010	INTEGER,							\
	NETMIG2011	INTEGER,							\
	NETMIG2012	INTEGER,							\
	RESIDUAL2010	INTEGER,							\
	RESIDUAL2011	INTEGER,							\
	RESIDUAL2012	INTEGER,							\
	RBIRTH2011	REAL,							\
	RBIRTH2012	REAL,							\
	RDEATH2011	REAL,							\
	RDEATH2012	REAL,							\
	RNATURALIN2011	REAL,							\
	RNATURALIN2012	REAL,							\
	RINTERNATIONALMIG2011	REAL,						\
	RINTERNATIONALMIG2012	REAL,						\
	RDOMESTICMIG2011	REAL,						\
	RDOMESTICMIG2012	REAL,						\
	RNETMIG2011	REAL,							\
	RNETMIG2012	REAL								\
)";


const char* createTable_PopEstStateCounty = "DROP TABLE IF EXISTS POP_EST_STATE_COUNTY;\
	CREATE TABLE POP_EST_STATE_COUNTY(						\
	SUMLEV		INTEGER REFERENCES SUMLEV(SUMLEV_Cd),				\
	REGION		INTEGER REFERENCES REGION(REGION_Cd),				\
	DIVISION	INTEGER REFERENCES DIVISION(DIVISION_Cd),			\
	STATE	INTEGER,							\
	COUNTY	INTEGER,							\
	STNAME	VARCHAR(255),								\
	CTYNAME	VARCHAR(255),								\
	CENSUS2010POP	INTEGER,							\
	ESTIMATESBASE2010	INTEGER,						\
	POPESTIMATE2010	INTEGER,							\
	POPESTIMATE2011	INTEGER,							\
	POPESTIMATE2012	INTEGER,							\
	NPOPCHG_2010	INTEGER,							\
	NPOPCHG_2011	INTEGER,							\
	NPOPCHG_2012	INTEGER,							\
	BIRTHS2010	INTEGER,							\
	BIRTHS2011	INTEGER,							\
	BIRTHS2012	INTEGER,							\
	DEATHS2010	INTEGER,							\
	DEATHS2011	INTEGER,							\
	DEATHS2012	INTEGER,							\
	NATURALINC2010	INTEGER,							\
	NATURALINC2011	INTEGER,							\
	NATURALINC2012	INTEGER,							\
	INTERNATIONALMIG2010	INTEGER,						\
	INTERNATIONALMIG2011	INTEGER,						\
	INTERNATIONALMIG2012	INTEGER,						\
	DOMESTICMIG2010	INTEGER,							\
	DOMESTICMIG2011	INTEGER,							\
	DOMESTICMIG2012	INTEGER,							\
	NETMIG2010	INTEGER,							\
	NETMIG2011	INTEGER,							\
	NETMIG2012	INTEGER,							\
	RESIDUAL2010	INTEGER,							\
	RESIDUAL2011	INTEGER,							\
	RESIDUAL2012	INTEGER,							\
	GQESTIMATESBASE2010	INTEGER,						\
	GQESTIMATES2010	INTEGER,							\
	GQESTIMATES2011	INTEGER,							\
	GQESTIMATES2012	INTEGER,							\
	RBIRTH2011	REAL,								\
	RBIRTH2012	REAL,								\
	RDEATH2011	REAL,								\
	RDEATH2012	REAL,								\
	RNATURALINC2011	REAL,								\
	RNATURALINC2012	REAL,								\
	RINTERNATIONALMIG2011	REAL,							\
	RINTERNATIONALMIG2012	REAL,							\
	RDOMESTICMIG2011	REAL,							\
	RDOMESTICMIG2012	REAL,							\
	RNETMIG2011		REAL,							\
	RNETMIG2012		REAL,							\
	PRIMARY KEY(STATE, COUNTY)							\
)";

const char* createTable_PopEstCitiesTowns = "DROP TABLE IF EXISTS POP_EST_CITIES_TOWNS;	\
	CREATE TABLE POP_EST_CITIES_TOWNS(						\
	SUMLEV	INTEGER REFERENCES SUMLEV(SUMLEV_Cd),				\
	STATE	INTEGER ,							\
	COUNTY	INTEGER	,							\
	PLACE	INTEGER	,							\
	COUSUB	INTEGER	,							\
	CONSIT	INTEGER	,							\
	NAME	VARCHAR(255),								\
	STNAME	VARCHAR(255),								\
	CENSUS2010POP	INTEGER,							\
	ESTIMATESBASE2010	INTEGER,						\
	POPESTIMATE2010	INTEGER,							\
	POPESTIMATE2011	INTEGER,								\
	PRIMARY KEY(STATE, COUNTY, PLACE, COUSUB, CONSIT)				\
)";


const char* createTable_PopEstStateAgeSexRaceOrigin = "DROP TABLE IF EXISTS POP_EST_STATE_AGE_SEX_RACE_ORIGIN;	\
	CREATE TABLE POP_EST_STATE_AGE_SEX_RACE_ORIGIN(					\
	SUMLEV	INTEGER REFERENCES SUMLEV(SUMLEV_Cd),				\
	REGION	INTEGER REFERENCES REGION(REGION_Cd),				\
	DIVISION	INTEGER REFERENCES DIVISION(DIVISION_Cd),				\
	STATE	INTEGER ,							\
	SEX	INTEGER REFERENCES SEX(SEX_Cd),					\
	ORIGIN	INTEGER	REFERENCES ORIGIN(ORIGIN_Cd),				\
	RACE	INTEGER	REFERENCES RACE(RACE_Cd),					\
	AGE	INTEGER ,							\
	CENSUS2010POP	INTEGER,							\
	ESTIMATESBASE2010	INTEGER,						\
	POPESTIMATE2010		INTEGER,						\
	POPESTIMATE2011		INTEGER,							\
	PRIMARY KEY(STATE, SEX, ORIGIN, RACE, AGE)				\
)";


const char* createTable_PopEstPrSexAge = "DROP TABLE IF EXISTS POP_EST_PR_SEX_AGE;	\
	CREATE TABLE POP_EST_PR_SEX_AGE(						\
	SUMLEV	INTEGER REFERENCES SUMLEV(SUMLEV_Cd),				\
	STATE INTEGER,									\
	NAME	VARCHAR(255),								\
	SEX	INTEGER REFERENCES SEX(SEX_Cd),					\
	AGE	INTEGER	,							\
	CENSUS2010POP	INTEGER,							\
	ESTIMATESBASE2010	INTEGER,						\
	POPESTIMATE2010		INTEGER,						\
	POPESTIMATE2011		INTEGER,							\
	PRIMARY KEY(SEX, AGE)								\
)";

const char* createTable_PopEstPrMunicipios = "DROP TABLE IF EXISTS POP_EST_PR_MUNICIPIOS;	\
	CREATE TABLE POP_EST_PR_MUNICIPIOS(						\
	SUMLEV	INTEGER REFERENCES SUMLEV(SUMLEV_Cd),				\
	MUNICIPIO	INTEGER	PRIMARY KEY,						\
	NAME		VARCHAR(255),							\
	ESTIMATESBASE2010	INTEGER,						\
	POPESTIMATE2010		INTEGER,						\
	POPESTIMATE2011		INTEGER,						\
	NPOPCHG_2010		INTEGER,						\
	NPOPCHG_2011		INTEGER,						\
	PPOPCHG_2010		INTEGER,						\
	PPOPCHG_2011		INTEGER,						\
	SRANK_ESTBASE2010	INTEGER,						\
	SRANK_POPEST2010	INTEGER,						\
	SRANK_POPEST2011	INTEGER,						\
	SRANK_NPCHG2010		INTEGER,						\
	SRANK_NPCHG2011		INTEGER,						\
	SRANK_PPCHG2010		INTEGER,						\
	SRANK_PPCHG2011		INTEGER							\
)";

const char* createTable_PopEstPrMunSexAge = "DROP TABLE IF EXISTS POP_EST_PR_MUN_SEX_AGE;	\
	CREATE TABLE POP_EST_PR_MUN_SEX_AGE(						\
	SUMLEV		INTEGER REFERENCES SUMLEV(SUMLEV_Cd),				\
	MUNICIPIO 	INTEGER	,						\
	NAME		VARCHAR(255),							\
	YEAR		INTEGER	,						\
	POPESTIMATE	INTEGER,							\
	POPEST_MALE	INTEGER,							\
	POPEST_FEM	INTEGER,							\
	UNDER5_TOT	INTEGER,							\
	UNDER5_MALE	INTEGER,							\
	UNDER5_FEM	INTEGER,							\
	AGE513_TOT	INTEGER,							\
	AGE513_MALE	INTEGER,							\
	AGE513_FEM	INTEGER,							\
	AGE1417_TOT	INTEGER,							\
	AGE1417_MALE	INTEGER,							\
	AGE1417_FEM	INTEGER,							\
	AGE1824_TOT	INTEGER,							\
	AGE1824_MALE	INTEGER,							\
	AGE1824_FEM	INTEGER,							\
	AGE16PLUS_TOT	INTEGER,							\
	AGE16PLUS_MALE	INTEGER,							\
	AGE16PLUS_FEM	INTEGER,							\
	AGE18PLUS_TOT	INTEGER,							\
	AGE18PLUS_MALE	INTEGER,							\
	AGE18PLUS_FEM	INTEGER,							\
	AGE1544_TOT	INTEGER,							\
	AGE1544_MALE	INTEGER,							\
	AGE1544_FEM	INTEGER,							\
	AGE2544_TOT	INTEGER,							\
	AGE2544_MALE	INTEGER,							\
	AGE2544_FEM	INTEGER,							\
	AGE4564_TOT	INTEGER,							\
	AGE4564_MALE	INTEGER,							\
	AGE4564_FEM	INTEGER,							\
	AGE65PLUS_TOT	INTEGER,							\
	AGE65PLUS_MALE	INTEGER,							\
	AGE65PLUS_FEM	INTEGER,							\
	AGE85PLUS_TOT	INTEGER,							\
	AGE85PLUS_MALE	INTEGER,							\
	AGE85PLUS_FEM	INTEGER,							\
	MEDIAN_AGE_TOT	INTEGER,							\
	MEDIAN_AGE_MALE	INTEGER,							\
	MEDIAN_AGE_FEM	INTEGER,							\
	PRIMARY KEY(MUNICIPIO, YEAR)							\
)";

const char* createTable_PopEstMetroMicro = "DROP TABLE IF EXISTS POP_EST_METRO_MICRO;	\
	CREATE TABLE POP_EST_METRO_MICRO(						\
	CBSA	INTEGER,								\
	MDIV	INTEGER,								\
	STCOU	INTEGER,								\
	NAME	VARCHAR(255),						\
	LSAD	VARCHAR(255),						\
	CENSUS2010POP	INTEGER,							\
	ESTIMATESBASE2010	INTEGER,						\
	POPESTIMATE2010	INTEGER,							\
	POPESTIMATE2011	INTEGER,							\
	NPOPCHG_2010	INTEGER,							\
	NPOPCHG_2011	INTEGER,							\
	NATURALINC2010	INTEGER,							\
	NATURALINC2011	INTEGER,							\
	BIRTHS2010	INTEGER,							\
	BIRTHS2011	INTEGER,							\
	DEATHS2010	INTEGER,							\
	DEATHS2011	INTEGER,							\
	NETMIG2010	INTEGER,							\
	NETMIG2011	INTEGER,							\
	INTERNATIONALMIG2010	INTEGER,						\
	INTERNATIONALMIG2011	INTEGER,						\
	DOMESTICMIG2010		INTEGER,						\
	DOMESTICMIG2011		INTEGER,						\
	RESIDUAL2010		INTEGER,						\
	RESIDUAL2011		INTEGER,							\
	PRIMARY KEY(NAME, LSAD)								\
)";

const char* createTable_HuUnitStateLevel = "DROP TABLE IF EXISTS HU_UNIT_STATE_LEVEL;	\
	CREATE TABLE HU_UNIT_STATE_LEVEL(						\
	SUMLEV		INTEGER REFERENCES SUMLEV(SUMLEV_Cd),				\
	STATE		INTEGER PRIMARY KEY,						\
	REGION		INTEGER REFERENCES REGION(REGION_Cd),				\
	DIVISION	INTEGER REFERENCES DIVISION(DIVISION_Cd),				\
	STNAME		VARCHAR(255),							\
	HUCENSUS2010	INTEGER,							\
	HUESTBASE2010	INTEGER,							\
	HUEST_2010	INTEGER,							\
	HUEST_2011	INTEGER								\
)";

const char* createTable_Region = "DROP TABLE IF EXISTS REGION;		\
	CREATE TABLE REGION(						\
	REGION_Cd	INTEGER	PRIMARY KEY,					\
	REGION_Desc	VARCHAR(255)					\
)";

const char* createTable_Division = "DROP TABLE IF EXISTS DIVISION;	\
	CREATE TABLE DIVISION(						\
	DIVISION_Cd	INTEGER	PRIMARY KEY,					\
	DIVISION_Name	VARCHAR(255)					\
)";

const char* createTable_Origin = "DROP TABLE IF EXISTS ORIGIN;	\
	CREATE TABLE ORIGIN(					\
	ORIGIN_Cd	INTEGER	PRIMARY KEY,				\
	ORIGIN_Desc	VARCHAR(255)				\
)";

const char* createTable_Race = "DROP TABLE IF EXISTS RACE;	\
	CREATE TABLE RACE(					\
	RACE_Cd		INTEGER	PRIMARY KEY,				\
	RACE_Desc	VARCHAR(255)				\
)";

const char* createTable_Sex = "DROP TABLE IF EXISTS SEX;\
	CREATE TABLE SEX(					\
	SEX_Cd	INTEGER	PRIMARY KEY,					\
	SEX_Desc	VARCHAR(255)				\
)";

const char* createTable_Sumlev = "DROP TABLE IF EXISTS SUMLEV;\
	CREATE TABLE SUMLEV(					\
	SUMLEV_Cd	INTEGER	PRIMARY KEY,				\
	SUMLEV_Desc	VARCHAR(255)					\
)";


}
